server:
  port: 8080

spring:
  application:
    name: easy-cache-test

# Easy Cache 配置
easy:
  cache:
    enabled: true
    local:
      enabled: true
      maximum-size: 10000
      initial-capacity: 100
      expire-after-write: 30
      time-unit: MINUTES
    redis:
      enabled: false  # 测试时禁用 Redis
    multi-level:
      enabled: true
      write-through: true
      async-write: false 